/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.twitter;

public class Entities {
	
	private Object media;
	
	public Object getMedia() {
		return media;
	}

	public void setMedia(Object media) {
		this.media = media;
	}


	private java.lang.Object[] urls;

 	public void setUrls(java.lang.Object[] urls) {
		this.urls = urls;
	}

	public java.lang.Object[] getUrls() {
		return urls;
	}

	
	private HashtagElement[] hashtags;

 	public void setHashtags(HashtagElement[] hashtags) {
		this.hashtags = hashtags;
	}

	public HashtagElement[] getHashtags() {
		return hashtags;
	}

	private java.lang.Object[] user_mentions;

 	public void setUser_mentions(java.lang.Object[] user_mentions) {
		this.user_mentions = user_mentions;
	}

	public java.lang.Object[] getUser_mentions() {
		return user_mentions;
	}

}