/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.twitter;

public class HashtagElement {
	
	private java.lang.Integer[] indices;

 	public void setIndices(java.lang.Integer[] indices) {
		this.indices = indices;
	}

	public java.lang.Integer[] getIndices() {
		return indices;
	}

	private java.lang.String text;

 	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}

}