/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.twitter;

public class Tweet {
	
	private java.lang.Boolean favorited;

 	public void setFavorited(java.lang.Boolean favorited) {
		this.favorited = favorited;
	}

	public java.lang.Boolean getFavorited() {
		return favorited;
	}
	private java.lang.String text;

 	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}
	private java.lang.String created_at;

 	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getCreated_at() {
		return created_at;
	}
	private java.lang.Object contributors;

 	public void setContributors(java.lang.Object contributors) {
		this.contributors = contributors;
	}

	public java.lang.Object getContributors() {
		return contributors;
	}
	private java.lang.Integer retweet_count;

 	public void setRetweet_count(java.lang.Integer retweet_count) {
		this.retweet_count = retweet_count;
	}

	public java.lang.Integer getRetweet_count() {
		return retweet_count;
	}
	private Object retweeted_status;
	public Object getRetweeted_status() {
		return retweeted_status;
	}

	public void setRetweeted_status(Object retweeted_status) {
		this.retweeted_status = retweeted_status;
	}

	private Boolean possibly_sensitive;

	public Boolean getPossibly_sensitive() {
		return possibly_sensitive;
	}

	public void setPossibly_sensitive(Boolean possibly_sensitive) {
		this.possibly_sensitive = possibly_sensitive;
	}

	private Boolean possibly_sensitive_editable;
	
	public Boolean getPossibly_sensitive_editable() {
		return possibly_sensitive_editable;
	}

	public void setPossibly_sensitive_editable(Boolean possibly_sensitive_editable) {
		this.possibly_sensitive_editable = possibly_sensitive_editable;
	}

	private java.lang.Boolean retweeted;

 	public void setRetweeted(java.lang.Boolean retweeted) {
		this.retweeted = retweeted;
	}

	public java.lang.Boolean getRetweeted() {
		return retweeted;
	}
	private java.lang.Object coordinates;

 	public void setCoordinates(java.lang.Object coordinates) {
		this.coordinates = coordinates;
	}

	public java.lang.Object getCoordinates() {
		return coordinates;
	}
	private java.lang.Object in_reply_to_screen_name;

 	public void setIn_reply_to_screen_name(java.lang.Object in_reply_to_screen_name) {
		this.in_reply_to_screen_name = in_reply_to_screen_name;
	}

	public java.lang.Object getIn_reply_to_screen_name() {
		return in_reply_to_screen_name;
	}


	private java.lang.Object geo;

 	public void setGeo(java.lang.Object geo) {
		this.geo = geo;
	}

	public java.lang.Object getGeo() {
		return geo;
	}

	private java.lang.Object in_reply_to_status_id_str;

 	public void setIn_reply_to_status_id_str(java.lang.Object in_reply_to_status_id_str) {
		this.in_reply_to_status_id_str = in_reply_to_status_id_str;
	}

	public java.lang.Object getIn_reply_to_status_id_str() {
		return in_reply_to_status_id_str;
	}

	private java.lang.Boolean truncated;

 	public void setTruncated(java.lang.Boolean truncated) {
		this.truncated = truncated;
	}

	public java.lang.Boolean getTruncated() {
		return truncated;
	}

	private Entities entities;

 	public void setEntities(Entities entities) {
		this.entities = entities;
	}

	public Entities getEntities() {
		return entities;
	}


	private java.lang.Object in_reply_to_user_id_str;

 	public void setIn_reply_to_user_id_str(java.lang.Object in_reply_to_user_id_str) {
		this.in_reply_to_user_id_str = in_reply_to_user_id_str;
	}

	public java.lang.Object getIn_reply_to_user_id_str() {
		return in_reply_to_user_id_str;
	}


	private java.lang.String id_str;

 	public void setId_str(java.lang.String id_str) {
		this.id_str = id_str;
	}

	public java.lang.String getId_str() {
		return id_str;
	}

	private java.lang.Object in_reply_to_status_id;

 	public void setIn_reply_to_status_id(java.lang.Object in_reply_to_status_id) {
		this.in_reply_to_status_id = in_reply_to_status_id;
	}

	public java.lang.Object getIn_reply_to_status_id() {
		return in_reply_to_status_id;
	}

	private java.lang.Object place;

 	public void setPlace(java.lang.Object place) {
		this.place = place;
	}

	public java.lang.Object getPlace() {
		return place;
	}

	private java.lang.Long id;

 	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getId() {
		return id;
	}

	private User user;

 	public void setUser(User user) {
		this.user = user;
	}

	public User getUser() {
		return user;
	}


	private java.lang.Object in_reply_to_user_id;

 	public void setIn_reply_to_user_id(java.lang.Object in_reply_to_user_id) {
		this.in_reply_to_user_id = in_reply_to_user_id;
	}

	public java.lang.Object getIn_reply_to_user_id() {
		return in_reply_to_user_id;
	}

	private java.lang.String source;

 	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.lang.String getSource() {
		return source;
	}

}