/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.twitter;

import com.fasterxml.jackson.annotation.JsonProperty;

public class User {

	private java.lang.Object follow_request_sent;

 	public void setFollow_request_sent(java.lang.Object follow_request_sent) {
		this.follow_request_sent = follow_request_sent;
	}

	public java.lang.Object getFollow_request_sent() {
		return follow_request_sent;
	}

	private java.lang.Boolean profile_background_tile;

 	public void setProfile_background_tile(java.lang.Boolean profile_background_tile) {
		this.profile_background_tile = profile_background_tile;
	}

	public java.lang.Boolean getProfile_background_tile() {
		return profile_background_tile;
	}


	private java.lang.Object url;

 	public void setUrl(java.lang.Object url) {
		this.url = url;
	}

	public java.lang.Object getUrl() {
		return url;
	}

	private java.lang.String profile_image_url_https;

 	public void setProfile_image_url_https(java.lang.String profile_image_url_https) {
		this.profile_image_url_https = profile_image_url_https;
	}

	public java.lang.String getProfile_image_url_https() {
		return profile_image_url_https;
	}

	private java.lang.Boolean default_profile;

 	public void setDefault_profile(java.lang.Boolean default_profile) {
		this.default_profile = default_profile;
	}

	public java.lang.Boolean getDefault_profile() {
		return default_profile;
	}

	private java.lang.String profile_background_image_url_https;

 	public void setProfile_background_image_url_https(java.lang.String profile_background_image_url_https) {
		this.profile_background_image_url_https = profile_background_image_url_https;
	}

	public java.lang.String getProfile_background_image_url_https() {
		return profile_background_image_url_https;
	}

	private java.lang.String profile_background_image_url;

 	public void setProfile_background_image_url(java.lang.String profile_background_image_url) {
		this.profile_background_image_url = profile_background_image_url;
	}

	public java.lang.String getProfile_background_image_url() {
		return profile_background_image_url;
	}


	private java.lang.String profile_sidebar_fill_color;

 	public void setProfile_sidebar_fill_color(java.lang.String profile_sidebar_fill_color) {
		this.profile_sidebar_fill_color = profile_sidebar_fill_color;
	}

	public java.lang.String getProfile_sidebar_fill_color() {
		return profile_sidebar_fill_color;
	}

	private java.lang.Object notifications;

 	public void setNotifications(java.lang.Object notifications) {
		this.notifications = notifications;
	}

	public java.lang.Object getNotifications() {
		return notifications;
	}

	
	private java.lang.String id_str;

 	public void setId_str(java.lang.String id_str) {
		this.id_str = id_str;
	}

	public java.lang.String getId_str() {
		return id_str;
	}

	private java.lang.String screen_name;

 	public void setScreen_name(java.lang.String screen_name) {
		this.screen_name = screen_name;
	}

	public java.lang.String getScreen_name() {
		return screen_name;
	}

	
	private java.lang.Boolean contributors_enabled;

 	public void setContributors_enabled(java.lang.Boolean contributors_enabled) {
		this.contributors_enabled = contributors_enabled;
	}

	public java.lang.Boolean getContributors_enabled() {
		return contributors_enabled;
	}


	private java.lang.Boolean verified;

 	public void setVerified(java.lang.Boolean verified) {
		this.verified = verified;
	}

	public java.lang.Boolean getVerified() {
		return verified;
	}

	private java.lang.String profile_image_url;

 	public void setProfile_image_url(java.lang.String profile_image_url) {
		this.profile_image_url = profile_image_url;
	}

	public java.lang.String getProfile_image_url() {
		return profile_image_url;
	}


	private java.lang.Object utc_offset;

 	public void setUtc_offset(java.lang.Object utc_offset) {
		this.utc_offset = utc_offset;
	}

	public java.lang.Object getUtc_offset() {
		return utc_offset;
	}


	private java.lang.Object time_zone;

 	public void setTime_zone(java.lang.Object time_zone) {
		this.time_zone = time_zone;
	}

	public java.lang.Object getTime_zone() {
		return time_zone;
	}

	private java.lang.Integer listed_count;

 	public void setListed_count(java.lang.Integer listed_count) {
		this.listed_count = listed_count;
	}

	public java.lang.Integer getListed_count() {
		return listed_count;
	}
	@JsonProperty("protected")
	private java.lang.Boolean protectedVar;

 	public void setProtectedVar(java.lang.Boolean protectedVar) {
		this.protectedVar = protectedVar;
	}

	public java.lang.Boolean getProtectedVar() {
		return protectedVar;
	}


	private java.lang.Boolean default_profile_image;

 	public void setDefault_profile_image(java.lang.Boolean default_profile_image) {
		this.default_profile_image = default_profile_image;
	}

	public java.lang.Boolean getDefault_profile_image() {
		return default_profile_image;
	}

	private java.lang.Integer friends_count;

 	public void setFriends_count(java.lang.Integer friends_count) {
		this.friends_count = friends_count;
	}

	public java.lang.Integer getFriends_count() {
		return friends_count;
	}

	private java.lang.Boolean geo_enabled;

 	public void setGeo_enabled(java.lang.Boolean geo_enabled) {
		this.geo_enabled = geo_enabled;
	}

	public java.lang.Boolean getGeo_enabled() {
		return geo_enabled;
	}

	private java.lang.Object location;

 	public void setLocation(java.lang.Object location) {
		this.location = location;
	}

	public java.lang.Object getLocation() {
		return location;
	}

	private java.lang.String lang;

 	public void setLang(java.lang.String lang) {
		this.lang = lang;
	}

	public java.lang.String getLang() {
		return lang;
	}

	private java.lang.Integer statuses_count;

 	public void setStatuses_count(java.lang.Integer statuses_count) {
		this.statuses_count = statuses_count;
	}

	public java.lang.Integer getStatuses_count() {
		return statuses_count;
	}

	private java.lang.String profile_link_color;

 	public void setProfile_link_color(java.lang.String profile_link_color) {
		this.profile_link_color = profile_link_color;
	}

	public java.lang.String getProfile_link_color() {
		return profile_link_color;
	}

	private java.lang.String created_at;

 	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getCreated_at() {
		return created_at;
	}

	private java.lang.String profile_background_color;

 	public void setProfile_background_color(java.lang.String profile_background_color) {
		this.profile_background_color = profile_background_color;
	}

	public java.lang.String getProfile_background_color() {
		return profile_background_color;
	}

	private java.lang.Object description;

 	public void setDescription(java.lang.Object description) {
		this.description = description;
	}

	public java.lang.Object getDescription() {
		return description;
	}

	private java.lang.Boolean profile_use_background_image;

 	public void setProfile_use_background_image(java.lang.Boolean profile_use_background_image) {
		this.profile_use_background_image = profile_use_background_image;
	}

	public java.lang.Boolean getProfile_use_background_image() {
		return profile_use_background_image;
	}

	private java.lang.Integer followers_count;

 	public void setFollowers_count(java.lang.Integer followers_count) {
		this.followers_count = followers_count;
	}

	public java.lang.Integer getFollowers_count() {
		return followers_count;
	}


	private java.lang.Object following;

 	public void setFollowing(java.lang.Object following) {
		this.following = following;
	}

	public java.lang.Object getFollowing() {
		return following;
	}


	private java.lang.Boolean show_all_inline_media;

 	public void setShow_all_inline_media(java.lang.Boolean show_all_inline_media) {
		this.show_all_inline_media = show_all_inline_media;
	}

	public java.lang.Boolean getShow_all_inline_media() {
		return show_all_inline_media;
	}

	
	private java.lang.Long id;

 	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getId() {
		return id;
	}

	private java.lang.Boolean is_translator;

 	public void setIs_translator(java.lang.Boolean is_translator) {
		this.is_translator = is_translator;
	}

	public java.lang.Boolean getIs_translator() {
		return is_translator;
	}

	private java.lang.Integer favourites_count;

 	public void setFavourites_count(java.lang.Integer favourites_count) {
		this.favourites_count = favourites_count;
	}

	public java.lang.Integer getFavourites_count() {
		return favourites_count;
	}

	private java.lang.String profile_text_color;

 	public void setProfile_text_color(java.lang.String profile_text_color) {
		this.profile_text_color = profile_text_color;
	}

	public java.lang.String getProfile_text_color() {
		return profile_text_color;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

	
	private java.lang.String profile_sidebar_border_color;

 	public void setProfile_sidebar_border_color(java.lang.String profile_sidebar_border_color) {
		this.profile_sidebar_border_color = profile_sidebar_border_color;
	}

	public java.lang.String getProfile_sidebar_border_color() {
		return profile_sidebar_border_color;
	}

}